<style lang="scss" >
</style>

<template>
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Album example</h1>

        <p class="lead text-muted">

        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
    </div>
</section>
</template>

<script>
export default {
    name: "BoketeJumbotron",
    data() {
        return {}
    },
    computed: {
        text() {
            return {}
        }
    }
}
</script>
