#%RAML 1.0
title: Main
version: v1
mediaType: application/json
baseUri: http://api.samplehost.com

uses:
  traits: traits/traits.raml
  resourceTypes: resourceTypes/crud-resourcetype.raml

types:
  Admindata:
    properties:
      admin_id:   integer
      admin_name: string

/admin:
  type:
    resourceTypes.collection:
      response-type: Admindata
      request-type: Admindata
  /{admin_id}:
    type:
      resourceTypes.id-collection:
        response-type: object
        request-type: object
