#%RAML 1.0 Library

types:

traits:
  HSC200:
    responses:
      200:
        description: Required is successed
        body:
          application/json:
            properties:
              status: integer

  HSC404:
    responses:
      404:
        description: Required properties missing or validation issues.
        body:
          application/json:
            properties:
              status: integer
