#%RAML 1.0 Library

usage: Common traits for the HTTP API

securitySchemes:
  sess: !include ../securitySchemes/security.raml

traits:
  sess:
    securedBy: sess

  set:
    queryParameters:
      _limit?:
        type: integer
      _sort?:
        type: string
