#%RAML 1.0
title: Example API

uses:
  traits:   ../traits/traits.raml
  response: ../traits/responses.raml

resourceTypes:
  collection:
    usage: This resourceType should be used for any collection of items
    description: The collection of <<resourcePathName>>
    get:
      is:  [traits.set]
      description: Get all <<resourcePathName>>, optionally filtered
      responses:
        200:
          body:
            application/json:
              type: <<response-type>>[]
    post:
      is: [response.HSC200,response.HSC404]
      description: Create a new <<resourcePathName | !singularize>>
      body:
        application/json:
          type: <<request-type>>

  id-collection:
    get:
      is:  [response.HSC404]
      description:
      responses:
        200:
          body:
            application/json:
              type: <<response-type>>
    put:
      is: [response.HSC200,response.HSC404]
      description:
      body:
        application/json:
          type: <<request-type>>
    delete:
      is: [response.HSC200,response.HSC404]
      description:
      body:
        application/json:
          type: <<request-type>>
